services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - kibanadata:/usr/share/kibana/data
    networks:
      - elastic
  
  logger-server:
    build: .
    container_name: logger-server
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    name: elastic
    driver: bridge
volumes:
  esdata:
    name: esdata
  kibanadata:
    name: kibanadata